# MSHTOCGNS_FOUND
# MSHTOCGNS_INCLUDE_DIR
# MSHTOCGNS_LIBRARIES

include (${MSHTOCGNS_DIR}/MSHtoCGNSConfig.cmake)
find_path (MSHTOCGNS_INCLUDE_DIR MSHtoCGNS/CgnsInterface/CgnsCreator.hpp HINTS ${MSHTOCGNS_DIR}/include NO_DEFAULT_PATH)
find_library (MSHTOCGNS_LIBRARY_DIR NAMES CgnsInterface.so CgnsInterface.a HINTS ${MSHTOCGNS_DIR}/libs NO_DEFAULT_PATH)

set (MSHTOCGNS_COMPONENTS Utilities MshInterface CgnsInterface FileMend)

set (MSHTOCGNS_FOUND FALSE)
if (MSHTOCGNS_INCLUDE_DIR)
    if (MSHTOCGNS_LIBRARY_DIR)
        set (MSHTOCGNS_FOUND TRUE)
        set (MSHTOCGNS_INCLUDE_DIR ${MSHTOCGNS_INCLUDE_DIR})
        set (MSHTOCGNS_LIBRARIES ${MSHTOCGNS_COMPONENTS})
    endif ()
endif ()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(MSHtoCGNS REQUIRED_VARS MSHTOCGNS_LIBRARY_DIR MSHTOCGNS_LIBRARIES MSHTOCGNS_INCLUDE_DIR VERSION_VAR ${MSHTOCGNS_VERSION})

mark_as_advanced(MSHTOCGNS_INCLUDE_DIR MSHTOCGNS_LIBRARY_DIR)
