# MSHTOCGNS_FOUND
# MSHTOCGNS_INCLUDE_DIR
# MSHTOCGNS_LIBRARIES

include (${MSHTOCGNS_DIR}/MSHtoCGNSConfigVersion.cmake)
include (${MSHTOCGNS_DIR}/MSHtoCGNSConfig.cmake)
include (${MSHTOCGNS_DIR}/MSHtoCGNSTargets.cmake)

include (FindPackageHandleStandardArgs)
find_package_handle_standard_args (MSHtoCGNS REQUIRED_VARS MSHTOCGNS_LIBRARY_DIR MSHTOCGNS_LIBRARIES MSHTOCGNS_INCLUDE_DIR VERSION_VAR PACKAGE_VERSION)
mark_as_advanced (MSHTOCGNS_INCLUDE_DIR MSHTOCGNS_LIBRARY_DIR)
